package com.ionicframework.penchoyaida233650.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BUSQUEDAS_TEMPORALES.
 */
public class BusquedasTemporales {

    private Long id;
    private String Titulo;
    private String content;
    private String link;
    private String pubdate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BusquedasTemporales() {
    }

    public BusquedasTemporales(Long id) {
        this.id = id;
    }

    public BusquedasTemporales(Long id, String Titulo, String content, String link, String pubdate) {
        this.id = id;
        this.Titulo = Titulo;
        this.content = content;
        this.link = link;
        this.pubdate = pubdate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitulo() {
        return Titulo;
    }

    public void setTitulo(String Titulo) {
        this.Titulo = Titulo;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getPubdate() {
        return pubdate;
    }

    public void setPubdate(String pubdate) {
        this.pubdate = pubdate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
