package com.ionicframework.penchoyaida233650.Fotos.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import com.ionicframework.penchoyaida233650.db.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table PHOTOSET.
*/
public class PhotosetDao extends AbstractDao<Photoset, Long> {

    public static final String TABLENAME = "PHOTOSET";

    /**
     * Properties of entity Photoset.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdAlbum = new Property(1, String.class, "idAlbum", false, "ID_ALBUM");
        public final static Property PrimaryPhoto = new Property(2, String.class, "primaryPhoto", false, "PRIMARY_PHOTO");
        public final static Property Secret = new Property(3, String.class, "secret", false, "SECRET");
        public final static Property Server = new Property(4, String.class, "server", false, "SERVER");
        public final static Property Farm = new Property(5, String.class, "farm", false, "FARM");
        public final static Property Photos = new Property(6, String.class, "photos", false, "PHOTOS");
        public final static Property Title = new Property(7, String.class, "title", false, "TITLE");
        public final static Property Description = new Property(8, String.class, "description", false, "DESCRIPTION");
        public final static Property Date_create = new Property(9, String.class, "date_create", false, "DATE_CREATE");
        public final static Property Date_update = new Property(10, String.class, "date_update", false, "DATE_UPDATE");
        public final static Property UrlImagenAlbum = new Property(11, String.class, "urlImagenAlbum", false, "URL_IMAGEN_ALBUM");
    };


    public PhotosetDao(DaoConfig config) {
        super(config);
    }
    
    public PhotosetDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PHOTOSET' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_ALBUM' TEXT," + // 1: idAlbum
                "'PRIMARY_PHOTO' TEXT," + // 2: primaryPhoto
                "'SECRET' TEXT," + // 3: secret
                "'SERVER' TEXT," + // 4: server
                "'FARM' TEXT," + // 5: farm
                "'PHOTOS' TEXT," + // 6: photos
                "'TITLE' TEXT," + // 7: title
                "'DESCRIPTION' TEXT," + // 8: description
                "'DATE_CREATE' TEXT," + // 9: date_create
                "'DATE_UPDATE' TEXT," + // 10: date_update
                "'URL_IMAGEN_ALBUM' TEXT);"); // 11: urlImagenAlbum
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PHOTOSET'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Photoset entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String idAlbum = entity.getIdAlbum();
        if (idAlbum != null) {
            stmt.bindString(2, idAlbum);
        }
 
        String primaryPhoto = entity.getPrimaryPhoto();
        if (primaryPhoto != null) {
            stmt.bindString(3, primaryPhoto);
        }
 
        String secret = entity.getSecret();
        if (secret != null) {
            stmt.bindString(4, secret);
        }
 
        String server = entity.getServer();
        if (server != null) {
            stmt.bindString(5, server);
        }
 
        String farm = entity.getFarm();
        if (farm != null) {
            stmt.bindString(6, farm);
        }
 
        String photos = entity.getPhotos();
        if (photos != null) {
            stmt.bindString(7, photos);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(9, description);
        }
 
        String date_create = entity.getDate_create();
        if (date_create != null) {
            stmt.bindString(10, date_create);
        }
 
        String date_update = entity.getDate_update();
        if (date_update != null) {
            stmt.bindString(11, date_update);
        }
 
        String urlImagenAlbum = entity.getUrlImagenAlbum();
        if (urlImagenAlbum != null) {
            stmt.bindString(12, urlImagenAlbum);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Photoset readEntity(Cursor cursor, int offset) {
        Photoset entity = new Photoset( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // idAlbum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // primaryPhoto
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // secret
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // server
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // farm
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // photos
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // title
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // description
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // date_create
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // date_update
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // urlImagenAlbum
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Photoset entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdAlbum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPrimaryPhoto(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSecret(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setServer(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFarm(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPhotos(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTitle(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDescription(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDate_create(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setDate_update(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setUrlImagenAlbum(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Photoset entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Photoset entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
