package com.ionicframework.penchoyaida233650.Fotos.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PHOTO_ALBUM.
 */
public class PhotoAlbum {

    private Long id;
    private String idPhoto;
    private String secret;
    private String server;
    private String farm;
    private String title;
    private String ispublic;
    private String idAlbum;
    private String urlImagenPhotoAlbum;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PhotoAlbum() {
    }

    public PhotoAlbum(Long id) {
        this.id = id;
    }

    public PhotoAlbum(Long id, String idPhoto, String secret, String server, String farm, String title, String ispublic, String idAlbum, String urlImagenPhotoAlbum) {
        this.id = id;
        this.idPhoto = idPhoto;
        this.secret = secret;
        this.server = server;
        this.farm = farm;
        this.title = title;
        this.ispublic = ispublic;
        this.idAlbum = idAlbum;
        this.urlImagenPhotoAlbum = urlImagenPhotoAlbum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdPhoto() {
        return idPhoto;
    }

    public void setIdPhoto(String idPhoto) {
        this.idPhoto = idPhoto;
    }

    public String getSecret() {
        return secret;
    }

    public void setSecret(String secret) {
        this.secret = secret;
    }

    public String getServer() {
        return server;
    }

    public void setServer(String server) {
        this.server = server;
    }

    public String getFarm() {
        return farm;
    }

    public void setFarm(String farm) {
        this.farm = farm;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getIspublic() {
        return ispublic;
    }

    public void setIspublic(String ispublic) {
        this.ispublic = ispublic;
    }

    public String getIdAlbum() {
        return idAlbum;
    }

    public void setIdAlbum(String idAlbum) {
        this.idAlbum = idAlbum;
    }

    public String getUrlImagenPhotoAlbum() {
        return urlImagenPhotoAlbum;
    }

    public void setUrlImagenPhotoAlbum(String urlImagenPhotoAlbum) {
        this.urlImagenPhotoAlbum = urlImagenPhotoAlbum;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
