package com.ionicframework.penchoyaida233650.Fotos.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PHOTO_DETALLE.
 */
public class PhotoDetalle {

    private Long id;
    private String idPhoto;
    private String secret;
    private String server;
    private String farm;
    private String dateuploaded;
    private String originalsecret;
    private String originalformat;
    private String title;
    private String description;
    private String posted;
    private String taken;
    private String lastupdate;
    private String url;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PhotoDetalle() {
    }

    public PhotoDetalle(Long id) {
        this.id = id;
    }

    public PhotoDetalle(Long id, String idPhoto, String secret, String server, String farm, String dateuploaded, String originalsecret, String originalformat, String title, String description, String posted, String taken, String lastupdate, String url) {
        this.id = id;
        this.idPhoto = idPhoto;
        this.secret = secret;
        this.server = server;
        this.farm = farm;
        this.dateuploaded = dateuploaded;
        this.originalsecret = originalsecret;
        this.originalformat = originalformat;
        this.title = title;
        this.description = description;
        this.posted = posted;
        this.taken = taken;
        this.lastupdate = lastupdate;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdPhoto() {
        return idPhoto;
    }

    public void setIdPhoto(String idPhoto) {
        this.idPhoto = idPhoto;
    }

    public String getSecret() {
        return secret;
    }

    public void setSecret(String secret) {
        this.secret = secret;
    }

    public String getServer() {
        return server;
    }

    public void setServer(String server) {
        this.server = server;
    }

    public String getFarm() {
        return farm;
    }

    public void setFarm(String farm) {
        this.farm = farm;
    }

    public String getDateuploaded() {
        return dateuploaded;
    }

    public void setDateuploaded(String dateuploaded) {
        this.dateuploaded = dateuploaded;
    }

    public String getOriginalsecret() {
        return originalsecret;
    }

    public void setOriginalsecret(String originalsecret) {
        this.originalsecret = originalsecret;
    }

    public String getOriginalformat() {
        return originalformat;
    }

    public void setOriginalformat(String originalformat) {
        this.originalformat = originalformat;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPosted() {
        return posted;
    }

    public void setPosted(String posted) {
        this.posted = posted;
    }

    public String getTaken() {
        return taken;
    }

    public void setTaken(String taken) {
        this.taken = taken;
    }

    public String getLastupdate() {
        return lastupdate;
    }

    public void setLastupdate(String lastupdate) {
        this.lastupdate = lastupdate;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
