package com.ionicframework.penchoyaida233650.Fotos.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PHOTOSET.
 */
public class Photoset {

    private Long id;
    private String idAlbum;
    private String primaryPhoto;
    private String secret;
    private String server;
    private String farm;
    private String photos;
    private String title;
    private String description;
    private String date_create;
    private String date_update;
    private String urlImagenAlbum;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Photoset() {
    }

    public Photoset(Long id) {
        this.id = id;
    }

    public Photoset(Long id, String idAlbum, String primaryPhoto, String secret, String server, String farm, String photos, String title, String description, String date_create, String date_update, String urlImagenAlbum) {
        this.id = id;
        this.idAlbum = idAlbum;
        this.primaryPhoto = primaryPhoto;
        this.secret = secret;
        this.server = server;
        this.farm = farm;
        this.photos = photos;
        this.title = title;
        this.description = description;
        this.date_create = date_create;
        this.date_update = date_update;
        this.urlImagenAlbum = urlImagenAlbum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdAlbum() {
        return idAlbum;
    }

    public void setIdAlbum(String idAlbum) {
        this.idAlbum = idAlbum;
    }

    public String getPrimaryPhoto() {
        return primaryPhoto;
    }

    public void setPrimaryPhoto(String primaryPhoto) {
        this.primaryPhoto = primaryPhoto;
    }

    public String getSecret() {
        return secret;
    }

    public void setSecret(String secret) {
        this.secret = secret;
    }

    public String getServer() {
        return server;
    }

    public void setServer(String server) {
        this.server = server;
    }

    public String getFarm() {
        return farm;
    }

    public void setFarm(String farm) {
        this.farm = farm;
    }

    public String getPhotos() {
        return photos;
    }

    public void setPhotos(String photos) {
        this.photos = photos;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDate_create() {
        return date_create;
    }

    public void setDate_create(String date_create) {
        this.date_create = date_create;
    }

    public String getDate_update() {
        return date_update;
    }

    public void setDate_update(String date_update) {
        this.date_update = date_update;
    }

    public String getUrlImagenAlbum() {
        return urlImagenAlbum;
    }

    public void setUrlImagenAlbum(String urlImagenAlbum) {
        this.urlImagenAlbum = urlImagenAlbum;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
