package com.ionicframework.penchoyaida233650.podcast_deportes.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table POSTCAD_DEPORTES.
 */
public class PostcadDeportes {

    private Long id;
    private String title;
    private String description;
    private String link;
    private String imagen;
    private String pubDate;
    private String author;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PostcadDeportes() {
    }

    public PostcadDeportes(Long id) {
        this.id = id;
    }

    public PostcadDeportes(Long id, String title, String description, String link, String imagen, String pubDate, String author) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.link = link;
        this.imagen = imagen;
        this.pubDate = pubDate;
        this.author = author;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getImagen() {
        return imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    public String getPubDate() {
        return pubDate;
    }

    public void setPubDate(String pubDate) {
        this.pubDate = pubDate;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
