package com.ionicframework.penchoyaida233650.videos.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table DETALLE_VIDEO.
 */
public class DetalleVideo {

    private Long id;
    private String etag;
    private String kind;
    private String publishedAt;
    private String channelId;
    private String title;
    private String description;
    private String defaultImg;
    private String medium;
    private String high;
    private String channelTitle;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DetalleVideo() {
    }

    public DetalleVideo(Long id) {
        this.id = id;
    }

    public DetalleVideo(Long id, String etag, String kind, String publishedAt, String channelId, String title, String description, String defaultImg, String medium, String high, String channelTitle) {
        this.id = id;
        this.etag = etag;
        this.kind = kind;
        this.publishedAt = publishedAt;
        this.channelId = channelId;
        this.title = title;
        this.description = description;
        this.defaultImg = defaultImg;
        this.medium = medium;
        this.high = high;
        this.channelTitle = channelTitle;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEtag() {
        return etag;
    }

    public void setEtag(String etag) {
        this.etag = etag;
    }

    public String getKind() {
        return kind;
    }

    public void setKind(String kind) {
        this.kind = kind;
    }

    public String getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(String publishedAt) {
        this.publishedAt = publishedAt;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDefaultImg() {
        return defaultImg;
    }

    public void setDefaultImg(String defaultImg) {
        this.defaultImg = defaultImg;
    }

    public String getMedium() {
        return medium;
    }

    public void setMedium(String medium) {
        this.medium = medium;
    }

    public String getHigh() {
        return high;
    }

    public void setHigh(String high) {
        this.high = high;
    }

    public String getChannelTitle() {
        return channelTitle;
    }

    public void setChannelTitle(String channelTitle) {
        this.channelTitle = channelTitle;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
