package com.ionicframework.penchoyaida233650.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ionicframework.penchoyaida233650.db.Portada;
import com.ionicframework.penchoyaida233650.db.Postcast;
import com.ionicframework.penchoyaida233650.db.DetallePodcast;
import com.ionicframework.penchoyaida233650.db.DetallePodcastPrincipal;
import com.ionicframework.penchoyaida233650.db.BusquedasTemporales;
import com.ionicframework.penchoyaida233650.db.Postcast_Principales;

import com.ionicframework.penchoyaida233650.db.PortadaDao;
import com.ionicframework.penchoyaida233650.db.PostcastDao;
import com.ionicframework.penchoyaida233650.db.DetallePodcastDao;
import com.ionicframework.penchoyaida233650.db.DetallePodcastPrincipalDao;
import com.ionicframework.penchoyaida233650.db.BusquedasTemporalesDao;
import com.ionicframework.penchoyaida233650.db.Postcast_PrincipalesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig portadaDaoConfig;
    private final DaoConfig postcastDaoConfig;
    private final DaoConfig detallePodcastDaoConfig;
    private final DaoConfig detallePodcastPrincipalDaoConfig;
    private final DaoConfig busquedasTemporalesDaoConfig;
    private final DaoConfig postcast_PrincipalesDaoConfig;

    private final PortadaDao portadaDao;
    private final PostcastDao postcastDao;
    private final DetallePodcastDao detallePodcastDao;
    private final DetallePodcastPrincipalDao detallePodcastPrincipalDao;
    private final BusquedasTemporalesDao busquedasTemporalesDao;
    private final Postcast_PrincipalesDao postcast_PrincipalesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        portadaDaoConfig = daoConfigMap.get(PortadaDao.class).clone();
        portadaDaoConfig.initIdentityScope(type);

        postcastDaoConfig = daoConfigMap.get(PostcastDao.class).clone();
        postcastDaoConfig.initIdentityScope(type);

        detallePodcastDaoConfig = daoConfigMap.get(DetallePodcastDao.class).clone();
        detallePodcastDaoConfig.initIdentityScope(type);

        detallePodcastPrincipalDaoConfig = daoConfigMap.get(DetallePodcastPrincipalDao.class).clone();
        detallePodcastPrincipalDaoConfig.initIdentityScope(type);

        busquedasTemporalesDaoConfig = daoConfigMap.get(BusquedasTemporalesDao.class).clone();
        busquedasTemporalesDaoConfig.initIdentityScope(type);

        postcast_PrincipalesDaoConfig = daoConfigMap.get(Postcast_PrincipalesDao.class).clone();
        postcast_PrincipalesDaoConfig.initIdentityScope(type);

        portadaDao = new PortadaDao(portadaDaoConfig, this);
        postcastDao = new PostcastDao(postcastDaoConfig, this);
        detallePodcastDao = new DetallePodcastDao(detallePodcastDaoConfig, this);
        detallePodcastPrincipalDao = new DetallePodcastPrincipalDao(detallePodcastPrincipalDaoConfig, this);
        busquedasTemporalesDao = new BusquedasTemporalesDao(busquedasTemporalesDaoConfig, this);
        postcast_PrincipalesDao = new Postcast_PrincipalesDao(postcast_PrincipalesDaoConfig, this);

        registerDao(Portada.class, portadaDao);
        registerDao(Postcast.class, postcastDao);
        registerDao(DetallePodcast.class, detallePodcastDao);
        registerDao(DetallePodcastPrincipal.class, detallePodcastPrincipalDao);
        registerDao(BusquedasTemporales.class, busquedasTemporalesDao);
        registerDao(Postcast_Principales.class, postcast_PrincipalesDao);
    }
    
    public void clear() {
        portadaDaoConfig.getIdentityScope().clear();
        postcastDaoConfig.getIdentityScope().clear();
        detallePodcastDaoConfig.getIdentityScope().clear();
        detallePodcastPrincipalDaoConfig.getIdentityScope().clear();
        busquedasTemporalesDaoConfig.getIdentityScope().clear();
        postcast_PrincipalesDaoConfig.getIdentityScope().clear();
    }

    public PortadaDao getPortadaDao() {
        return portadaDao;
    }

    public PostcastDao getPostcastDao() {
        return postcastDao;
    }

    public DetallePodcastDao getDetallePodcastDao() {
        return detallePodcastDao;
    }

    public DetallePodcastPrincipalDao getDetallePodcastPrincipalDao() {
        return detallePodcastPrincipalDao;
    }

    public BusquedasTemporalesDao getBusquedasTemporalesDao() {
        return busquedasTemporalesDao;
    }

    public Postcast_PrincipalesDao getPostcast_PrincipalesDao() {
        return postcast_PrincipalesDao;
    }

}
