package com.ionicframework.penchoyaida233650.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PORTADA.
 */
public class Portada {

    private Long id;
    private String song;
    private String artist;
    private String album;
    private String albumArt;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Portada() {
    }

    public Portada(Long id) {
        this.id = id;
    }

    public Portada(Long id, String song, String artist, String album, String albumArt) {
        this.id = id;
        this.song = song;
        this.artist = artist;
        this.album = album;
        this.albumArt = albumArt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSong() {
        return song;
    }

    public void setSong(String song) {
        this.song = song;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getAlbumArt() {
        return albumArt;
    }

    public void setAlbumArt(String albumArt) {
        this.albumArt = albumArt;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
